name: Build FFmpeg Audio Libraries

# Grant the runner permission to fetch marketplace actions
permissions:
  contents: read      # already there by default
  actions: read       # <— this line lets it download actions/upload-artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-audio-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android NDK
        run: |
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ndk.zip
          unzip -q ndk.zip -d android-ndk

      - name: Make build script executable
        run: chmod +x build-audio-convertor-ffmpeg.sh

      - name: Run audio build script
        run: ./build-audio-convertor-ffmpeg.sh

      - name: Verify 16 KB page alignment
        run: |
          echo "Checking PT_LOAD p_align for all .so files…"
          for so in output/arm64-v8a/*.so; do
            echo "  → $so"
            # field 9 is the Align column
            p_aligns=$(readelf -l "$so" | awk '/LOAD/ {print $9}' | sort -u)
            echo "    p_align = $p_aligns"
            if ! echo "$p_aligns" | grep -q '^0x00004000$'; then
              echo "::error ::$so is NOT 16 KB–aligned (found: $p_aligns)"
              exit 1
            fi
          done
          echo "✅ All .so files are 16 KB aligned"

      - name: Upload .so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-audio-libs
          path: output/**/*.so
