name: Build FFmpeg Audio Libraries

# Grant the runner permission to fetch marketplace actions
permissions:
  contents: read      # already there by default
  actions: read       # <— this line lets it download actions/upload-artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-audio-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android NDK
        run: |
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ndk.zip
          unzip -q ndk.zip -d android-ndk

      - name: Make build script executable
        run: chmod +x build-audio-convertor-ffmpeg.sh

      - name: Run audio build script
        run: ./build-audio-convertor-ffmpeg.sh

      - name: Verify 16 KB page alignment
        run: |
          echo "Checking PT_LOAD p_align for all .so files…"
          for so in output/arm64-v8a/*.so; do
            echo "  → $so"
            # grab LOAD lines that have 0x00004000 in the p_align column
            matches=$(readelf -l "$so" | grep 'LOAD' | grep '0x00004000' || true)
            if [ -n "$matches" ]; then
              echo "    ✅ 16 KB alignment entries:"
              echo "$matches"
            else
              echo "::error ::$so is NOT 16 KB aligned"
              echo "    full LOAD table for debugging:"
              readelf -l "$so" | grep 'LOAD'
              exit 1
            fi
          done
          echo "✅ All .so files passed the 16 KB alignment check"

      - name: Upload .so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-audio-libs
          path: output/**/*.so
