name: Build FFmpeg Audio Libraries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-audio-libs:
    runs-on: ubuntu-latest
    env:
      API: 24
      ANDROID_NDK_URL: https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
      # location inside workspace where NDK will be extracted
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk/android-ndk-r25c

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android NDK
        run: |
          curl -sSL "$ANDROID_NDK_URL" -o ndk.zip
          unzip -q ndk.zip -d android-ndk

      - name: Make build script executable
        run: chmod +x build-audio-convertor-ffmpeg.sh

      - name: Run audio build script
        run: |
          ./build-audio-convertor-ffmpeg.sh

      - name: Upload .so artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-audio-libs
          path: output/**/*.so
