name: Build FFmpeg Audio Libraries

# Grant the runner permission to fetch marketplace actions
permissions:
  contents: read      # already there by default
  actions: read       # <— this line lets it download actions/upload-artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-audio-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android NDK
        run: |
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ndk.zip
          unzip -q ndk.zip -d android-ndk

      - name: Make build script executable
        run: chmod +x build-audio-convertor-ffmpeg.sh

      - name: Run audio build script
        run: ./build-audio-convertor-ffmpeg.sh

      - name: Upload .so artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-audio-libs
          path: output/**/*.so
